/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bromelliti.odysseus;

/**
 *
 * @author Neri
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
        setVisibleAll(false);
    }
    
    
    
    private void setVisibleAll(boolean visible){ //Rende invisibile/visible i bottoni e i label
        jButtonCura.setVisible(visible);
        jButtonAttacca.setVisible(visible);
        jButtonRicarica.setVisible(visible);
        jLabelCHP.setVisible(visible);
        jLabelCMP.setVisible(visible);
        jLabelCSP.setVisible(visible);
        jLabelHP.setVisible(visible);
        jLabelSP.setVisible(visible);
        jLabelMP.setVisible(visible);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRicarica = new javax.swing.JButton();
        jButtonAttacca = new javax.swing.JButton();
        jButtonCura = new javax.swing.JButton();
        jLabelMP = new javax.swing.JLabel();
        jLabelHP = new javax.swing.JLabel();
        jLabelSP = new javax.swing.JLabel();
        jLabelCHP = new javax.swing.JLabel();
        jLabelCSP = new javax.swing.JLabel();
        jLabelCMP = new javax.swing.JLabel();
        jButtonInizia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonRicarica.setText("Ricarica");

        jButtonAttacca.setText("Attacca");

        jButtonCura.setText("Cura");

        jLabelMP.setForeground(new java.awt.Color(51, 51, 255));
        jLabelMP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMP.setText("MP");

        jLabelHP.setForeground(new java.awt.Color(255, 0, 0));
        jLabelHP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHP.setText("HP");

        jLabelSP.setBackground(new java.awt.Color(51, 51, 51));
        jLabelSP.setForeground(new java.awt.Color(102, 255, 45));
        jLabelSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSP.setText("SP");

        jLabelCHP.setForeground(new java.awt.Color(255, 0, 0));
        jLabelCHP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelCSP.setForeground(new java.awt.Color(102, 255, 45));
        jLabelCSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelCMP.setForeground(new java.awt.Color(51, 51, 255));
        jLabelCMP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButtonInizia.setText("Inizia");
        jButtonInizia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inizia(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelCHP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelHP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                    .addComponent(jButtonAttacca))
                .addGap(138, 138, 138)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonInizia, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelSP, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                        .addComponent(jLabelCSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelMP, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                        .addComponent(jLabelCMP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButtonRicarica, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMP)
                    .addComponent(jLabelHP)
                    .addComponent(jLabelSP))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCHP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCSP, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelCMP, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButtonInizia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRicarica)
                    .addComponent(jButtonCura)
                    .addComponent(jButtonAttacca))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Inizia(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inizia
        setVisibleAll(true);
    }//GEN-LAST:event_Inizia

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAttacca;
    private javax.swing.JButton jButtonCura;
    private javax.swing.JButton jButtonInizia;
    private javax.swing.JButton jButtonRicarica;
    private javax.swing.JLabel jLabelCHP;
    private javax.swing.JLabel jLabelCMP;
    private javax.swing.JLabel jLabelCSP;
    private javax.swing.JLabel jLabelHP;
    private javax.swing.JLabel jLabelMP;
    private javax.swing.JLabel jLabelSP;
    // End of variables declaration//GEN-END:variables
}
